## ResultType
- 에러가 발생하는 경우, 에러를 따로 외부에 던지는 것이 아니라, 리턴타입 자체를 Result Type (success ,failure ) 으로 구현해서 함수의 성공과 실패의 정보를 담아서 리턴한다
- Result Type 은 열거형이다
 #### ResultType 의 타입을 활용한 에러의 처리
 - 기존 에러 처리
```swift
enum HeightError : Error {
	case maxHeight
	case minHeight
}

func checkingHeight(height:Int) throws -> Bool {
	if height > 190 {
		throw HeightError.maxHeight
	} else if height < 130 {
		throw HeightError.minHeight
	} else {
		if Height >= 160 {
			return true
		} else {
			return false
		}
	}
}

do {
	let _ = try checkingHeight(height:200)
}catch {
	print("놀이기구 타는 것 불가능")
}
```

- 에러는 동일하게 정의되어 있다고 가정
- Result 타입에는 성공 / 실패 했을 경우에 대한 정보가 다 들어있음
```swift

//throws 키워드를 사용할 수 없음 
func resultTypeCheckingHeight(height: Int ) -> Result<Bool, HeightError> {
	if height > 190 {
		return Result.failure(HeightError.maxHeight)
	}else if height < 130 {
		return Result.failure(HeightError.minHeight)
	} else {
		if height >= 160 }
			return Result.success(true)
		} else {
			return Result.success(false)
		}
	}
}

// try 를 사용할 필요가 없음
let result = resultTypeCheckingHeight(height:200)

switch result {
	case .sucess (let data) :
		print("결과값은 \(data) 입니다" )
	case .failure (let data) :
		printdata)
}
```

#### ResultType 활용
```swift
do {
	let data = try result.get()
	print("결과 \(data)")
}catch {
	print(error)
}
```