## 에러처리 문법
#### 에러의 이해
-  컴파일 에러 - 스위프트 문법과 관련된 에러
-  런타임 에러 - 프로그램이 실행되는 동안 발생하며, 앱이 강제 종료, 해당 에러를 미리 처리해두면 강제종료 되지 않음
#### 에러처리의 과정
- 에러 정의
```swift
enum HeightError : Error {
	case maxHeight
	case minHeight
}
```

- 에러가 발생할 수 있는 함수에 대한 정의
```swift
func checkingHeight(height:Int) throws -> Bool {
	if height > 190 {
		throw HeightError.maxHeight
	}else if height < 130 {
		throw HeightError.minHeight
	}else{
		if height >= 160 {
			return true
		}else{
			return false
		}
	}
}
```

- 에러가 발생할 수 있는 함수의 처리(함수의 실행) --> 기존과는 다름
```swift
do{
	var result = try checkingHeight(height:160)
	print("결과값 \(result)")

} catch {
	print("에러가 발생한 경우")	
}
```

#### 에러를 처리하는 방법
- 정석처리 방법
```swift
do{
	let isChecked = try checkingHeight( height: 200)

	if isChecked {
		print("가능")
	} else {
		print("불가")
	}

} catch {
	print("놀이기구 이용불가")	
}
```

- try? 옵셔널 트라이 -> 옵셔널 타입으로 리턴
	- 정상적인 경우 -> 리턴타입으로 리턴
	- 에러발생하면 -> nil 리턴
```swift
let isChecked : Bool? = try? checkingHeight(height:200)
if let result = isChecked {
	// code
}
```

- try! (Forced 트라이) -> 에러가 날 수 없는 경우에만 사용 가능
	- 정상적인 경우 -> 리턴타입으로 리턴
	- 에러가 발생하면 -> 런타임 에러
```swift
let isChecked : Bool = try! checkingHeight(height:200)
```

#### catch 문을 사용한 처리법
- 패턴이 있는 경우
```swift
do{
	let isChecked = try checkingHeight( height: 200)
} catch HeightError.maxHeight where ... {
	print("키가 너무 큼")	
} catch HeightError.minHeight where .... {
	print("키가 너무 작음")
}
```

- 패턴이 없는 경우
```swift
do {
   let isChecked = try checkingHeight( height: 200)
} catch {
	print(error)
	print(error.localizedDescription) // 앱에서 지역설정된. 에러

	if let error = error as? HeightError{
		switch error {
		case .maxHeight :
			print("키너무큼")
		case .minHeight :
			print("너무작음")
		}
	}
}
```


- Swift 5.3 이후
```swift
do {
   let isChecked = try checkingHeight( height: 200)
} catch HeightError.maxHeight, HeightError.minHeight {
	print("불가")
}
```
## 에러를 던지는 함수 처리
##### 에러 정의
```swift
enum SomeError : Error {
	case aError
}

func throwingFunc() throws{
	throw SomeError.aError
}

do {
	try throwingFunc()
} catch {
	print(error)
}
```

#### 일반적인 함수로 처리
- 함수 내부에서 do-catch 문으로 에러를 처리
- 발생한 에러를 catch 블럭에서 받아서 알맞은 처리
```swift
func handleError(){
	do {
		try throwingFunc()
	} catch {
		print(error)
	}
}

handleError()
```

#### throwing 함수로 에러 다시 던지기
- 함수내에서 에러를 직접처리하지 못한 경우, 에러를 다시 던질 수 있음
```swift
func handleError1() throws{
	try throwingFunc() // do-catch 블럭이 없어도 에러를 밖으로 던질 수 있음
}

do {
	try handleError1()
} catch {
	print(error)
}
```

#### rethrowing 함수로 에러를 다시 던지기 (rethrows 키워드)
- 에러를 던지는 throwing 함수를 파라미터로 받는 경우 내부에서 다시 에러를 던지기 가능
- rethrow 키워드 필요(Rethrowing 메서드)

- 다시 에러를 던지는 함수
```swift
func someFunction1(callback : () throws -> Void) rethrows {
	try callback() // do-catch 블럭 생략가능
}
```

- 다시 에러를 던지는 함수 - 에러 변환
```swift
func someFunction2(callback : () throws -> Void) rethrows {
	enum ChangedError : Error {
		case cError
	}

	do {
		try callback()
	} catch {
		throw ChangedErorr.cError
	}

}
```

- 실제 에러를 다시 던지는 (rethrowing) 함수를 처리하는 부분
```swift
do {
	try someFunction1(callback: throwingFunc)
}catch {
	print(error)
}


do {
	try somFunction2(callback : throwingFunc)
}catch {
	print(error)
}
```

## 메서드 생성자 throw 키워드 적용
- 에러를 던질수 있는 메서드는 throwing 메서드 
- 에러를 던질수 있는 생성자는  throwing 생성자
```swift
enum NameError : Error {
	case NoName
}
```

- 에러를 던질수 있는 생성자
```swift
class Course {
	var name : String

	init(name : String) throws{
		if name == ""{
			throw NameError.noName
		} else {
			self.name = name
			print("생성")
		}
	}
}

do {
	let courseT = try Course(name : "스위프트")
} catch NameError.noName {
	print("이름이 없어 수업생성에 실패")
}

```

- 생성자 메서드 재정의
	- 상위 throws -> 하위 throws :가능
	- 상위 throws -> 하위 일반 : 불가
	- 상위 throws -> 하위 rethrows : 가능
	- 상위 rethrows -> 하위 throws : 불가능 
	- throwing 메서드와 rethrow 메서드를 비교하면 rethrowing 메서드 범위가 더 작음
	- 일반 함수가 throwing 보다 범위가 더 큼

#### 예시
- 에러의 정의 및 데이터 구성
```swift

enum VendingMachineUserError: Error {
    case invalidSelection
    case insufficientFunds(coinsNeeded: Int)
    case outOfStock
}

enum VendingMachineMechanicalError : Error {
    case btnError(btn : String)
    case coolingError
    case heatingError
    case technicalError
}

enum VeiwUserError : Error {
    case anotherBtnPressed
    case contactAdmin
}
  
struct Item {
    var price : Int
    var count : Int
}
  
var vendingInventory = [
    "Candy Bar": Item(price: 1200, count: 7),
    "Chips": Item(price: 1000, count: 4),
    "Pretzels": Item(price: 700, count: 5)
]

// 에러체크 변수
var btnCheck = "none"
var technicalError = "none"
var coolingError = "none"
var heatingError = "none"

// 관리자 에러메세지 저장
var errorArr = [[Date:String]]()

```

- 내부에러 (if 문 활용)
```swift
// 내부 기계 에러

var errorCheckedVendingMachine = {
    if btnCheck != "none" {
        throw VendingMachineMechanicalError.btnError(btn: btnCheck)
    }

    if technicalError != "none" {
        throw VendingMachineMechanicalError.technicalError
    }

    if coolingError != "none" {
        throw VendingMachineMechanicalError.coolingError
    }

    if heatingError != "none" {
        throw VendingMachineMechanicalError.heatingError
    }
}
```

- 사용자 에러 분리 (guard 문을 활용한 throw 전달)
```swift
// 이용자 에러
var errorUser = { name, coin in
    guard var item = vendingInventory[name] else {
        throw VendingMachineError.invalidSelection
    }

    guard item.count > 0 else {
        throw VendingMachineError.outOfStock
    }

    guard item.price <= coin else {
        throw VendingMachineError
		      .insufficientFunds(coinsNeeded: item.price - coin)
    }
    return item
}


```

- 자판기 로직
```swift
func vendingMachindUsedThrow(_ name : String, _ coin : Int) throws {
    try errorCheckedVendingMachine()
    var item = try errorUser( name, coin)
    item.count -= 1
    vendingInventory[name] = item
}
```

- rethrows 를 활용한 사용자 에러변환 
```swift
func userViewErrorCode(_ name :String, 
					   _ coin : Int, 
					   closure : (String, Int) throws -> Void) rethrows {

    do {
        try closure(name, coin)
    }catch VendingMachineMechanicalError.coolingError,
           VendingMachineMechanicalError.heatingError,
           VendingMachineMechanicalError.technicalError,
           VendingMachineMechanicalError.btnError {
        throw VeiwUserError.contactAdmin
        
    }catch VendingMachineUserError.invalidSelection {
        throw VeiwUserError.anotherBtnPressed
    }
}
```

- 에러 메세지의 분리 - 사용자
```swift
func userView (name : String, coin : Int ) throws {
    do{
        try userViewErrorCode(name, 500, closure: vendingMachindUsedThrow)
    }catch VeiwUserError.contactAdmin {
        print("관리지에게 연락")
    }catch VeiwUserError.anotherBtnPressed {
        print("다른 버튼을 눌러주세요")
    }catch VendingMachineUserError.insufficientFunds(let coin){
        print("\(coin) 부족합니다")
    }catch VendingMachineUserError.outOfStock {
        print("품절입니다")
    }
}
```
- 에러메세지 분리 - 관리자
```swift
func adminView(_ name :String, _ coin : Int) throws {
    var tempDic = [Date : String]()
    func inputDicToArr( _ msg : String){
        tempDic[Date.now] = msg
        errorArr.append(tempDic)
        print(msg)
    }

    do{
        try errorCheckedVendingMachine()
        try vendingMachindUsedThrow(name, coin)
    }catch VendingMachineMechanicalError.btnError(let btn){
        inputDicToArr("\(btn) 버튼 이상")
    }catch VendingMachineMechanicalError.technicalError{
        inputDicToArr("기기 이상! 점검 필요")
    }catch VendingMachineMechanicalError.heatingError {
        inputDicToArr("온장장비 이상")
    }catch VendingMachineMechanicalError.coolingError {
        inputDicToArr("냉방장치 이상")
    }catch VendingMachineUserError.outOfStock{
        inputDicToArr( "품절")
    }catch VendingMachineUserError.insufficientFunds(let coinNeeded){
		inputDicToArr("\(coinNeeded) 입금금액부족")
    }
}

```